---

- hosts: compute
  remote_user: root

  tasks:
    - name: Modify GRUB
      lineinfile:
        dest: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on default_hugepagesz={{default_hugepagesz}} hugepagesz={{hugepagesz}}"'

    - name: Update GRUB
      shell: {{item}}
      with_items:
        - grub2-mkconfig -o /boot/grub2/grub.cfg
        - dracut --force

    - name: Create dir for huge pages
      shell: mkdir /mnt/huge

    - name: Add hugepage dev in fstab
      lineinfile:
        dest: /etc/fstab
        line: 'nodev /mnt/huge hugetlbfs pagesize={{hugepagesz}}B 0 0'
        backup: True

    - name: Permissions to hugepages service
      shell: chmod +x /usr/lib/systemd/hugetlb-reserve-pages

    - name: Start service hugepages
      service:
        name: hugetlb-gigantic-pages
        state: started

    - name: Disable KSM services
      service:
        name: {{item}}
        state: stopped
        with_items:
          - ksmtuned
          - ksm
      notify:
        - reboot

  handlers:

    - name: reboot
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true
